### ISSUE TITLE
Explicitly language 

### ISSUE THREAD

**Issue by ghost** [kazimmt/RVX-Features#11]
Remove it or ban filter app
![Screenshot_20240721_211957](https://github.com/user-attachments/assets/34741873-e867-44b3-8fb9-39de6a9a6ffb)
. Kindly please have 🙏🙏🙏🙏 . Fix update it please.  I don't why explicitly language it doesn't don't why please vanished it .

**Comment by KobeW50** [comment]
The ReVanced.net manager is unrelated to this repository.

(On a personal note, I would recommend not using it because it may be malicious. It is not made by the ReVanced team)

**Comment by ghost** [comment]
![Screenshot_20240723_141244](https://github.com/user-attachments/assets/903b09b1-b0fe-44c1-bd56-92f1b467ba5c)
, my apologies to repeat. Remote access it please 
Parental advisory explicit content why it show ,why it dissappear it vanish ,why pick catalogs in youtube Revanced search it don't well it open explicit I don't why it do it ,ticket number .my apologies.  Clean version add all video please billion or millions could add it please, I don't feel comfortable, I just don't hear exlucuse word just see app well please,,what this Revanced is . Block third party in Revanced, we use different approach please,  if you understand.  My apologies.  You kindly give welcome appear this youtube please

**Comment by ghost** [comment]
![Screenshot_20240723_155136_YouTube](https://github.com/user-attachments/assets/7a244a91-f09c-495a-88ec-99c80f9c19cd)
,https://youtu.be/7BOBrOreeY4,https://youtu.be/I-sZs1XPHvw, still pop up explicitly language, kindly turn off , I don't why it not vanish.  Cleaning speaker language please. See ain't to you,my apologies

**Comment by ghost** [comment]
Kindly fix Playlist where call in media . Need Kindly help please 
![Screenshot_20240723_171924_YouTube](https://github.com/user-attachments/assets/91109e5f-47c8-4fb0-9392-3388ffd4ba37), not put default kindly remove. Thanks issue play show Playlist ain't lie to you,my apologies need your help COPPA Language please kindly please thanks .my apologies if am say right. Thank lots

**Comment by Spacellary** [comment]
I too will point that this manager is **not related** to the actual ReVanced or RVX projects, I'd recommend reproducing whatever issue you may have with a patched application from a supported method for report in the appropriate patches repo.

**Comment by ghost** [comment]
You help with this application please need your applies please

**Comment by KobeW50** [comment]
> You help with this application please need your applies please 

Spacellary and I are saying that you opened this bug report in the wrong place.

**Comment by ghost** [comment]
Thank you ,kindly do feel ,thank you. How feel.  Become customer believe that please need your help. If join
