### ISSUE TITLE
Typo

### ISSUE THREAD

**Issue by KobeW50** [kazimmt/RVX-Features#4]
Subscriptions is spelled incorrectly. 

Rvx features > YT Rvx > Shorts > Hide subscriptions button

https://github.com/kazimmt/RVX-Features/blob/website/RVX-Features/YT-RVX-features/Shorts.md#L71

https://kazimmt.github.io/RVX-Features/rvx-features/yt-rvx-features/shorts/#hide-subscrioptions-button

**Comment by kazimmt** [comment]
Thanks

**Comment by KobeW50** [comment]
Np, ur project is awesome
