### ISSUE TITLE
Reddit ReVanced and Reddit RVX separation isn't clear

### ISSUE THREAD

**Issue by KobeW50** [kazimmt/RVX-Features#5]
**Issue**

Having Reddit RV and Reddit RVX on the same page is confusing, and there's no info for each patch whether the patch exists in Reddit RV, Reddit RVX, or both.

**Solution**

There are 2 possible solutions:

1. Move the entire Reddit page to the RVX section, and forget about Reddit RV (just like how YT and YTM is only for RVX). Remember to change the page link if you do this.

2. Keep the RVX patches in the current Reddit page, but add a label to each patch to specify whether the patch is for RV, RVX, or both. Also, the page label (pictured below) would need to be renamed to `Reddit RV(X) Features` or `Reddit RV/RVX Features`.

![SmartSelect_20240105_144600_Chrome.jpg](https://github.com/kazimmt/RVX-Features/assets/84587632/9d3ae110-c197-4ddd-b141-e520c62c8c86)

**Comment by kazimmt** [comment]
Thanks for your feedback.
I was offline for long. Sure I'll change it soon.

**Comment by kazimmt** [comment]
Fixed with https://github.com/kazimmt/kazimmt.github.io/commit/d53d324e85c507dafab11117d8d271015808d433
