### ISSUE TITLE
No support for playlists download

### ISSUE THREAD

**Issue by tushargautam681** [kazimmt/RVX-Features#7]
If there is a full playlist download option is available then it could a great help for many students out here

**Comment by KobeW50** [comment]
Seal and YTDLnis can download playlists. Copy the link to the playlist and paste it into the search bar thingy on the homepage of those apps. I think the playlists need to be public in order to share them. 

Also for seal, you'll need to enable playlists downloads in the General settings.

You may need to enable a little checkbox too when ypu are downloading it. Sorry, i havent downloaded in a while. Hope this helps

**Comment by tushargautam681** [comment]
> Seal and YTDLnis can download playlists. Copy the link to the playlist and paste it into the search bar thingy on the homepage of those apps. I think the playlists need to be public in order to share them. 
> 
> Also for seal, you'll need to enable playlists downloads in the General settings.
> 
> You may need to enable a little checkbox too when ypu are downloading it. Sorry, i havent downloaded in a while. Hope this helps

You didn't get that. I was talking about playlist downloading via rvx downloader.You can head to @samdeveloper website or samapkstore. He embeded your rvx downloader in his youtube pro apk which is a very good customizable apk. Best for students. It will be very kind if any how you can add this functionality in rvx downloder. Thanks!

**Comment by KobeW50** [comment]
> You didn't get that. I was talking about playlist downloading via rvx downloader.You can head to @samdeveloper website or samapkstore. He embeded your rvx downloader in his youtube pro apk which is a very good customizable apk. Best for students. It will be very kind if any how you can add this functionality in rvx downloder. Thanks!

This repository is only to provide documentation for Rvx and revanced features. Rvx is developed by [inotia00](https://github.com/inotia00).

The developer you speak of is not official.

There are NO official Revanced or Revanced Extended apks with a built-in downloader. They only have external downloader support. The apk you are using is either a  heavily modified Revanced or Revanced Extended app, or more likely, an entirely different app. I would not trust it. I strongly suggest uninstalling any software you got from that developer and getting RVX, Revanced, (or ReX) apks through legitimate means, which is by patching them yourself. If you need help with that i can provide you with resources.
