### ISSUE TITLE
Please review as soon as possible!

### ISSUE THREAD

**Issue by tushargautam681** [kazimmt/RVX-Features#8]
You didn't get that. I was talking about playlist downloading via rvx downloader.You can head to @samdeveloper website or samapkstore. He embeded your rvx downloader in his youtube pro apk which is a very good customizable apk. Best for students. It will be very kind if any how you can add this functionality in rvx downloder. Thanks!

_Originally posted by @tushargautam681 in https://github.com/kazimmt/RVX-Features/issues/7#issuecomment-1975245213_

**Comment by kazimmt** [comment]
ReVanced will never incorporate such a feature as it may potentially lead to legal ramifications for the project.

The individual you referred to is not affiliated with ReVanced. They independently added a download feature.
