### ISSUE TITLE
Update the YT RVX Features guide

### ISSUE THREAD

**Issue by ArcherLegend** [kazimmt/RVX-Features#9]
After inotia00 archived his patches for RevancedExtended YT-Advanced first and anddea then have kept updating their branch of inotia00's patches and the project is currently supported by anddea.

With the latest versions of anddea's patches new settings are being added and they are missing from your Wiki therefore given how good it already is it would be a pity not to keep it updated.

**Comment by kazimmt** [comment]
Suppresed by #20
